---
- name: Criar e compartilhar pasta NFC-e
  hosts: PDV
  gather_facts: false

  tasks:
    - name: Criar pasta NFC-e
      ansible.windows.win_file:
        path: C:\PDV\NFCe
        state: directory

    - name: Criar arquivo XML
      ansible.windows.win_copy:
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <nfce>
            <status>teste</status>
          </nfce>
        dest: C:\PDV\NFCe\nfce-001.xml

    - name: Dar permissão NTFS para IEUser
      ansible.windows.win_acl:
        path: C:\PDV\NFCe
        user: 'MSEDGEWIN10\IEUser'
        rights: Modify
        type: allow
        state: present
        inherit: ContainerInherit,ObjectInherit
        propagation: None

    - name: Compartilhar pasta NFC-e
      ansible.windows.win_share:
        name: NFCe
        description: Compartilhamento NFC-e
        path: C:\PDV\NFCe
        state: present
        full: 'MSEDGEWIN10\IEUser'
